#!/bin/sh

uci set network.lan.ipaddr=192.168.16.1
uci commit network

uci set system.@system[0].timezone=WIB-7
uci set system.@system[0].zonename=Asia/Jakarta
uci commit system

if ! grep -q ".php=/usr/bin/php-cgi" /etc/config/uhttpd; then
	uci set uhttpd.main.ubus_prefix='/ubus'
	uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
	uci set uhttpd.main.index_page='cgi-bin/luci'
	uci add_list uhttpd.main.index_page='index.html'
	uci add_list uhttpd.main.index_page='index.php'
	uci commit uhttpd
	/etc/init.d/uhttpd restart
fi

exit 0
